brand:
  name: 'Emily Risinger PLLC'
  email: 'help@emilyrisinger.com'
  phone: '612.564.5717 Fax: 651.447.5137'
  intro:
    heading: Exposure Therapy for OCD and Anxiety Disorders
Behavioral Interventions for BFRBs and Tourettes
  specialties:
    heading: Specialties
    subheading: Anxiety Disorders Treated
    specialty:
      - heading: OCD
        text: Obsessive-Compulsive
      - heading: Specific Phobias
        text: Agoraphobia
      - heading: Social Anxiety Disorder
        text: Fear of social situations
      - heading: Panic
        text: Anxiety Attacks
  services:
    heading: Services
    subheading: Understand Our Role
    service:
      - heading: Individual Counseling
        text: >
          We offer individual therapy for adults, adolescents, and children. We specialize
          in the treatment of anxiety issues through the use of Cognitive Behavioral Therapy
          (CBT) and Exposure & Response Prevention (ERP). Both CBT and ERP are evidence based
          practices that have been shown to provide strong long term benefits in the treatment
          of anxiety.
      - heading: Cost and Insurance
        text: >
          We offer transparent flat fees for our services: $125 per therapy session.
          Clients are encouraged to confirm out-of-network coverage options
          with their insurance provider; we do not bill insurance payers. Therapy sessions are 50
          minutes. We recommend clients plan up to two hours for diagnostic assessments. Our therapists
          can help you facilitate out-of-network coverage with your insurance provider, including
          the use of superbills. Unfortunately we do not offer a sliding scale fee or pro-bono
          appointments at this time.
  team:
    heading: Meet Our Therapist
    subheading: Learn Who I Am
    members:
      - name: Emily Risinger
        role: MS, ATR, LPCC
        img: img/team/emily-risinger.jpg
        text: >
          Emily works with with adults and children struggling with anxiety. She uses CBT, ERP,
          and Art therapy to support her clients in developing effective coping skills. Knowing
          that accountability is key in treating anxiety she takes a caring but firm approach with
          her clients and their support system.
  connect:
    heading: Book A Provider
    subheading: >
      We’re here for you when you need us! Call us to schedule an appointment, or send us
      an email and we’ll get back to you as soon as possible.
nav:
  - title: Specialties
    url: '#specialties'
  - title: Services
    url: '#services'
  - title: About
    url: '#about'
  - title: Connect
    url: '#connect'
copyright: Copyright &copy; Emily Risinger PLLC 2019-2021
quicklinks:
  - title: Privacy Policy
    url: '#'
  - title: Terms of Use
    url: '#'
